(use-modules (oop goops)
	     (nnw core generic)
	     (nnw core view)
	     (nnw core view document)
	     (nnw core block)	     
	     (nnw core parser)
	     (sxml match)
	     (srfi srfi-1)
             (srfi srfi-64))

(test-begin "logs/parser")

;; (test-group "parse a document"
;;   (let* ((view-source "This is a document source in Block 1.\nThis is the second line in Block 2")
;; 	 (parsed (parse view-source <document> '())))
;;     (test-assert "parsed returns a pair" (pair? parsed))
;;     (test-assert "parsed has 2 blocks" (= (length (cdr parsed)) 2))
;;     (test-assert "car parsed is document" (is-a? (car parsed) <view>))
;;     (test-assert "cdr parsed all is block" (every (lambda (b) (is-a? b <block>)) (cdr parsed)))))

(test-group "parse-text basic functionality"
  (let ((result (parse-text "line1\nline2\n\nline3")))
    (sxml-match-let (((view (@ (type ,tv)
			       (name ,nv))
		       (block (@ (type ,tb1)) (p ,line1))
		       (block (@ (type ,tb2)) (p ,line2))
		       (block (@ (type ,tb3)) (p ,line3)))
		     result))
		    (test-equal "first block content" "line1" line1)
		    (test-equal "second block content" "line2" line2)
		    (test-equal "third block content" "line3" line3)
		    (test-equal "first block type" "text" tb1)
		    (test-equal "second block type" "text" tb2)
		    (test-equal "third block type" "text" tb3)
		    (test-equal "View Type" "document" tv)
		    (test-equal "View Name" "Untitled Document" nv))))

(test-group "input->views+blocks functionality"
  (let* ((input-sxml '(view (@ (type "document") (name "Test Document"))
                            (block (@ (type "text") (description "Block 1") (tags "tag1 tag2 tag3")) (p "First line"))
                            (block (@ (type "text") (description "Block 2") (tags "tag1 tag2 tag3")) (p "Second line"))))
         (result (input->views+blocks input-sxml)))
    (test-assert "result is a pair" (pair? result))
    (test-assert "car result is list of views" (list? (car result)))
    (test-assert "cdr result is list of blocks" (list? (cdr result)))
    (test-equal "has one view" 1 (length (car result)))
    (test-equal "has two blocks" 2 (length (cdr result)))
    (test-assert "view is document type" (is-a? (caar result) <document>))
    (test-equal "view's type is document " 'document (get-type (caar result)))
    (test-equal "view name matches" "Test Document" (get-name (caar result)))
    (test-assert "all blocks are text type" (every (lambda (b) (is-a? b <text>)) (cdr result)))
    (test-equal "block's tags match" '("tag1" "tag2" "tag3") (get-tags (cadr result)))))

(test-end "logs/parser")
