(define-module (nnw core parser)
  #:use-module (nnw core generic)
  #:use-module (nnw core utils)
  #:use-module (nnw core view)
  #:use-module (nnw core type)
  #:use-module (oop goops)
  #:use-module (sxml match)
  #:export (parse-text))

(define (replace-input-view view)
  (if (equal? (car view) 'view)
      '(view-blocks ,(input->views+blocks view))
      view))

(define (replace-input-views input)
  (sxml-match-let (((view . ,children)
		    input))
    (let ((modified-children (map replace-input-view children)))
      `(view ,@children))))

(define-method (input->views+blocks (input <list>))
  (sxml-match-let (((view (@ (type ,type) . ,otr) . ,children)
		    (replace-input-view input)))
    (input->views+blocks input (string->view-type type))))

(define (parse-text-block tags lines)
  (map (lambda (line)
    `(block (@ (type "text")
	       ,@(if (not (null? tags))
		     `((tags ,(string-join tags " ")))
		     '()))
	    (p ,line))) lines))

(define* (parse-text source #:key (tags '())
                                  (view-id #f)
				  (view-type "document")
				  (view-name "Untitled Document")
				  (view-metadata '()))
  (let* ((lines (filter (lambda (line) (not (string=? line "")))
			(string-split source #\newline)))
	 (blocks (parse-text-block tags lines)))
    `(view (@ (type ,view-type)
              (name ,view-name)
	      ,@view-metadata
	      ,@(if view-id `(id ,view-id) '()))
           ,@blocks)))
