(define-module (nnw core parser org)
  #:use-module (nnw core generic)
  #:use-module (nnw core utils)
  #:use-module (nnw core view)
  #:use-module (nnw core type)
  #:use-module (orgfile)
  #:use-module (orgfile node)
  #:use-module (oop goops)
  #:use-module (sxml match)
  #:use-module (srfi srfi-1)
  #:export (parse-org))

(define (document->input d)
  (if (document-node? d)
      (fold+convert (node-children d))
      (error "not a document node")))

(define (node->input n)
  (cond ((section-node? n) (section-node->input n))
        ((list-node? n) (list-node->input n))
        ((item-node? n) (item-node->input n))
        ((paragraph-node? n) (paragraph-node->input n))
        ((drawer-node? n) (drawer-node->input n))
        ((link-node? n) (link-node->input n))
        ((text-node? n) (text-node->input n))
        (else (error "unrecognized node"))))

(define (section-node->input n)
  (let* ((level (node-get-data n 'level))
         (headline (node-get-data n 'headline))
         (tags (node-get-data n 'tags)))
    `(view (@ (name ,headline)
	      (level ,(number->string level))
	      (tags ,(string-join tags " "))) ,@(fold+convert (node-children n)))))

(define (list-node->input n)
  (let* ((ordered? (node-get-data n 'ordered))
         (list-type (if ordered? 'ol 'ul)))
    `(,list-type ,(fold+convert (node-children n)))))

(define (item-node->input n)
  `(li ,(fold+convert (node-children n))))

(define (paragraph-node->input n)
  (let ((folded (fold+convert (node-children n))))
    `(p ,@folded)))

(define (drawer-node->input n)
  (let* ((name (node-get-data n 'name))
         (metadata (drawer-get-metadata n))
         (children (node-children n))
         (dl-content (map (lambda (pair)
                           `((dt ,(symbol->string (car pair)))
                             (dd ,(cdr pair))))
                         metadata)))
    `(details (summary ,name)
              (dl ,@(apply append dl-content))
              ,@(fold+convert children))))

(define (link-node->input n)
  (let ((url (node-get-data n 'url))
        (desc (node-get-data n 'description)))
    `(a (@ (href ,url)) ,desc)))

(define (text-node->input n)
  (string-join (reverse (node-children n))))

(define (fold+convert lst)
  (define (convert+cons elem prev)
    (cons (node->input elem) prev))
  (fold convert+cons '() lst))

;; (define (parse-text-block tags lines)
;;   (map (lambda (line)
;;     `(block (@ (type "text")
;; 	       ,@(if (not (null? tags))
;; 		     `((tags ,(string-join tags " ")))
;; 		     '()))
;; 	    (p ,line))) lines))

(define* (parse-org source #:key (tags '())
                                  (view-id #f)
				  (view-type "list-view")
				  (view-name "Untitled Document")
				  (view-metadata '()))
  (let* ((lines (filter (lambda (line) (not (string=? line "")))
			(string-split source #\newline)))
	 (blocks (parse-text-block tags lines)))
    `(view (@ (type ,view-type)
              (name ,view-name)
	      ,@view-metadata
	      ,@(if view-id `((id ,view-id)) '()))
           ,@blocks)))
